from __future__ import annotations

import asyncio
from collections.abc import Callable, Iterator
from urllib.parse import urljoin

from playwright.async_api import Page, Response

from app.core.exceptions import UnsupportedPageState
from app.storage.database import Database
from app.storage.models import Comment
from app.xhs import selectors
from app.xhs.risk_detector import detect_risk_control


class HistoryScanner:
    """Observe the currently open history/interaction page and persist safe matches.

    It never calls a private API itself. It only inspects JSON responses generated by
    ordinary page navigation/scrolling, and only accepts records whose author ID
    exactly equals the logged-in user ID.
    """

    def __init__(
        self,
        page: Page,
        database: Database,
        current_user_id: str,
        on_discovered: Callable[[int], None] | None = None,
        should_pause: Callable[[], bool] | None = None,
    ):
        self.page = page
        self.database = database
        self.current_user_id = current_user_id
        self.on_discovered = on_discovered or (lambda _count: None)
        self.should_pause = should_pause or (lambda: False)
        self._seen: set[tuple[str, str]] = set()
        self._response_error: str | None = None

    async def scan_my_comment_history(self, max_stagnant_rounds: int = 5) -> tuple[int, bool]:
        if not self.page.url.startswith("https://www.xiaohongshu.com/"):
            raise UnsupportedPageState("请先在 Edge 中打开小红书的评论互动记录页面")
        if not await self._is_sent_comment_history_page():
            raise UnsupportedPageState(
                "当前页面不是可验证的“我发出的评论”列表。当前小红书网页版未发现该入口，"
                "程序已停止扫描，不会把 0 条误报为账号没有历史评论。"
            )
        await detect_risk_control(self.page)
        response_tasks: set[asyncio.Task] = set()

        def schedule_response(response: Response) -> None:
            task = asyncio.create_task(self._on_response(response))
            response_tasks.add(task)
            task.add_done_callback(response_tasks.discard)

        self.page.on("response", schedule_response)
        discovered_before = self.database.counts()["discovered"]
        stagnant = 0
        scan_complete = False
        try:
            while stagnant < max_stagnant_rounds and not self.should_pause():
                before = self.database.counts()["discovered"]
                await self._extract_from_dom()
                scan_complete = await self._has_explicit_end_marker()
                if scan_complete:
                    break
                await self.page.mouse.wheel(0, 1400)
                await self.page.wait_for_timeout(1_500)
                await detect_risk_control(self.page)
                after = self.database.counts()["discovered"]
                stagnant = stagnant + 1 if after == before else 0
            total = self.database.counts()["discovered"]
            self.database.set_state("scan_complete", "true" if scan_complete else "false")
            self.database.set_state("last_scanned_url", self.page.url)
            return total - discovered_before, scan_complete
        finally:
            self.page.remove_listener("response", schedule_response)
            if response_tasks:
                await asyncio.gather(*response_tasks, return_exceptions=True)

    async def _on_response(self, response: Response) -> None:
        content_type = response.headers.get("content-type", "")
        if "json" not in content_type or not response.ok:
            return
        try:
            payload = await response.json()
            for item in self._walk_dicts(payload):
                comment = self._comment_from_mapping(item)
                if comment:
                    self._persist(comment)
        except Exception as exc:
            # Response parsing is opportunistic; never interrupt the page request.
            self._response_error = type(exc).__name__

    async def _extract_from_dom(self) -> None:
        # DOM fallback only accepts containers exposing a stable comment ID and an
        # exact author profile link. No nth-child or positional guessing.
        for generic in selectors.COMMENT_CONTAINERS:
            try:
                elements = self.page.locator(generic)
                count = min(await elements.count(), 500)
            except Exception:
                continue
            for index in range(count):
                element = elements.nth(index)
                comment_id = await element.get_attribute("data-comment-id") or await element.get_attribute("data-id")
                author_href = await element.locator(selectors.COMMENT_AUTHOR_LINK).first.get_attribute("href")
                if not comment_id or not author_href or f"/user/profile/{self.current_user_id}" not in author_href:
                    continue
                note_link = await element.locator('a[href*="/explore/"]').first.get_attribute("href")
                feed_id = self._feed_id_from_url(note_link or self.page.url)
                if not feed_id:
                    continue
                content = (await element.inner_text(timeout=1_000))[:4000]
                self._persist(Comment(
                    id=None, feed_id=feed_id, comment_id=comment_id,
                    parent_comment_id=None, comment_type="comment", content=content,
                    note_url=urljoin(self.page.url, note_link or self.page.url),
                    created_at=None, author_id=self.current_user_id,
                ))

    def _comment_from_mapping(self, item: dict) -> Comment | None:
        comment_id = self._first(item, "comment_id", "commentId", "id")
        author_id = self._nested_first(item, ("user_id", "userId", "author_id", "authorId"))
        if not comment_id or not author_id or str(author_id) != self.current_user_id:
            return None
        feed_id = self._first(item, "note_id", "noteId", "feed_id", "feedId")
        note_url = self._first(item, "note_url", "noteUrl", "target_url", "targetUrl", "url")
        if not feed_id and note_url:
            feed_id = self._feed_id_from_url(str(note_url))
        if not feed_id:
            return None
        if not note_url:
            note_url = f"https://www.xiaohongshu.com/explore/{feed_id}"
        note_url = urljoin("https://www.xiaohongshu.com/", str(note_url))
        if not note_url.startswith("https://www.xiaohongshu.com/"):
            return None
        parent_id = self._first(item, "parent_comment_id", "parentCommentId", "root_comment_id", "rootCommentId")
        content = self._first(item, "content", "text", "comment_content", "commentContent") or ""
        created_at = self._first(item, "created_at", "create_time", "createTime", "time")
        return Comment(
            id=None, feed_id=str(feed_id), comment_id=str(comment_id),
            parent_comment_id=str(parent_id) if parent_id else None,
            comment_type="reply" if parent_id else "comment", content=str(content),
            note_url=note_url, created_at=str(created_at) if created_at else None,
            author_id=self.current_user_id,
        )

    def _persist(self, comment: Comment) -> None:
        key = (comment.feed_id, comment.comment_id)
        if key in self._seen:
            return
        self._seen.add(key)
        self.database.upsert_comment(comment)
        self.on_discovered(self.database.counts()["discovered"])

    async def _has_explicit_end_marker(self) -> bool:
        try:
            text = (await self.page.locator("body").inner_text(timeout=2_000))[-5000:]
            return any(marker in text for marker in selectors.HISTORY_END_TEXT)
        except Exception:
            return False

    async def _is_sent_comment_history_page(self) -> bool:
        for marker in selectors.SENT_COMMENT_HISTORY_TEXT:
            try:
                if await self.page.get_by_text(marker, exact=True).first.is_visible(timeout=500):
                    return True
            except Exception:
                continue
        return False

    @staticmethod
    def _walk_dicts(value: object) -> Iterator[dict]:
        if isinstance(value, dict):
            yield value
            for child in value.values():
                yield from HistoryScanner._walk_dicts(child)
        elif isinstance(value, list):
            for child in value:
                yield from HistoryScanner._walk_dicts(child)

    @staticmethod
    def _first(item: dict, *keys: str):
        for key in keys:
            if key in item and item[key] not in (None, ""):
                return item[key]
        return None

    @staticmethod
    def _nested_first(item: dict, keys: tuple[str, ...]):
        direct = HistoryScanner._first(item, *keys)
        if direct:
            return direct
        for container_key in ("user", "author", "owner", "comment_user"):
            container = item.get(container_key)
            if isinstance(container, dict):
                value = HistoryScanner._first(container, *keys, "id")
                if value:
                    return value
        return None

    @staticmethod
    def _feed_id_from_url(url: str) -> str | None:
        for marker in ("/explore/", "/discovery/item/"):
            if marker in url:
                return url.split(marker, 1)[1].split("?", 1)[0].split("/", 1)[0]
        return None
